/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as KanjiKanjiImport } from './routes/kanji/$kanji'

// Create Virtual Routes

const KanjiIndexLazyImport = createFileRoute('/kanji/')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const KanjiIndexLazyRoute = KanjiIndexLazyImport.update({
  path: '/kanji/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/kanji/index.lazy').then((d) => d.Route))

const KanjiKanjiRoute = KanjiKanjiImport.update({
  path: '/kanji/$kanji',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/kanji/$kanji': {
      preLoaderRoute: typeof KanjiKanjiImport
      parentRoute: typeof rootRoute
    }
    '/kanji/': {
      preLoaderRoute: typeof KanjiIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  KanjiKanjiRoute,
  KanjiIndexLazyRoute,
])

/* prettier-ignore-end */
