/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PlayIndexImport } from './routes/play/index'
import { Route as KanjiKanjiImport } from './routes/kanji/$kanji'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlayIndexRoute = PlayIndexImport.update({
  path: '/play/',
  getParentRoute: () => rootRoute,
} as any)

const KanjiKanjiRoute = KanjiKanjiImport.update({
  path: '/kanji/$kanji',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/kanji/$kanji': {
      preLoaderRoute: typeof KanjiKanjiImport
      parentRoute: typeof rootRoute
    }
    '/play/': {
      preLoaderRoute: typeof PlayIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  KanjiKanjiRoute,
  PlayIndexRoute,
])

/* prettier-ignore-end */
