/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as KanjiPlayIndexImport } from './routes/kanji-play/index'
import { Route as KanjiPlayPlayIndexImport } from './routes/kanji-play/play/index'
import { Route as KanjiPlayKanjiKanjiImport } from './routes/kanji-play/kanji/$kanji'

// Create/Update Routes

const KanjiPlayIndexRoute = KanjiPlayIndexImport.update({
  path: '/kanji-play/',
  getParentRoute: () => rootRoute,
} as any)

const KanjiPlayPlayIndexRoute = KanjiPlayPlayIndexImport.update({
  path: '/kanji-play/play/',
  getParentRoute: () => rootRoute,
} as any)

const KanjiPlayKanjiKanjiRoute = KanjiPlayKanjiKanjiImport.update({
  path: '/kanji-play/kanji/$kanji',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kanji-play/': {
      preLoaderRoute: typeof KanjiPlayIndexImport
      parentRoute: typeof rootRoute
    }
    '/kanji-play/kanji/$kanji': {
      preLoaderRoute: typeof KanjiPlayKanjiKanjiImport
      parentRoute: typeof rootRoute
    }
    '/kanji-play/play/': {
      preLoaderRoute: typeof KanjiPlayPlayIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  KanjiPlayIndexRoute,
  KanjiPlayKanjiKanjiRoute,
  KanjiPlayPlayIndexRoute,
])

/* prettier-ignore-end */
